![0.jfif](attachment:0.jfif)

<div style="direction:rtl">
خب خب، درسته که نامپای ستون فقرات دیتا ساینیه، ولی ما کارامون رو با دست و چشم و پا انجام میدیم نه با خود ستون فقرات. برای همین تو این بخش زیاد تمرینای از جنس مساله نداریم و بیشتر تمرینامون حول تسلط به ابزار ها و متد های این کتابخونه است.
<div style="direction:rtl">
برای شروع، کتابخونه ی نامپای رو ایمپورت کنید.

In [1]:
import numpy as np

<div style="direction:rtl">
یه آرایه ی متشکل از 10 تا صفر بسازید.

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<div style="direction:rtl">
یه آرایه ی متشکل از 10 تا یک بسازید.

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<div style="direction:rtl">
یه آرایه ی متشکل از 10 تا پنج بسازید.

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

<div style="direction:rtl">
یه آرایه ی متشکل از اعداد ده تا پنجاه بسازید.

In [6]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

<div style="direction:rtl">
یه آرایه ی متشکل از اعداد زوج بین ده تا پنجاه بسازید.

In [7]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

<div style="direction:rtl">
یه ماتریس سه در سه با مقادیر 0 تا 8 بسازید.

In [8]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<div style="direction:rtl">
یه ماتریس سه در سه قطری بسازید.

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<div style="direction:rtl">
یه ماتریس سه در سه با اعداد رندوم بسازید.

In [10]:
np.random.rand(3, 3)

array([[0.83054607, 0.54946081, 0.98275919],
       [0.26064054, 0.06783044, 0.34292666],
       [0.47610584, 0.5706664 , 0.26814346]])

<div style="direction:rtl">
یه ماتریس سه در سه با اعداد رندومی بسازید که به شکل نرمال حول 0 توزیع شده باشند.

In [11]:
np.random.randn(3, 3)

array([[ 0.96799285, -0.33166593, -1.88796257],
       [ 0.28811712, -1.05110084,  0.90887185],
       [-1.28241661, -0.00272137,  0.3202054 ]])

<div style="direction:rtl">
با دو روش مختلف دقیقا ماتریس زیر رو بسازید.

In [17]:
np.arange(0.01, 1.01, 0.01).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [19]:
np.linspace(0.01, 1, 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

<div style="direction:rtl">
آرایه ای بسازید که شامل 20 تا عدد با فاصله های مساوی بین 0 و 1 باشه.

In [20]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

<div style="direction:rtl">
ابتدا ماتریس زیر را با نام mat بسازید و سپس تکه های خواسته شده از ماتریس در هر بخش را به دست آورید.

In [21]:
mat = np.arange(1, 26).reshape(5, 5)

In [23]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
mat[2::, 1::]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [27]:
mat[3][4]

20

In [31]:
mat[:3, 1].reshape(-1, 1)

array([[ 2],
       [ 7],
       [12]])

In [32]:
mat[4]

array([21, 22, 23, 24, 25])

In [33]:
mat[3::]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
mat[[0, 2, 4]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [35]:
mat[:, [0, 2, 4]]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25]])

In [50]:
mat[[0, 2, 4], :][:,[0, 2, 4]]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

<div style="direction:rtl">
با مراجعه به بخش fancy از جلسه ی پیش، سعی کنید تکه ماتریس بالا را با روش اول آقای جانفدا هم محاسبه کنید و ایراد آن روش را در پایین بنویسید.

In [ ]:
# This Slice is the Same Code of Above, just Written Like Janfada First Method

array([[ 1, 11, 21],
       [ 3, 13, 23],
       [ 5, 15, 25]])

In [54]:
mat[[[0], [2], [4]],[0 ,2 ,4]]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

<div style="direction:rtl">
تفاوت این روش با روش درست در این است که :...

<div style="direction:rtl">
جمع تک تک عناصر موجود در ماتریس را با استفاده از دو روش (یک بار متد و یک بار فانکشن) به دست آورید.

In [55]:
def matrix_Sum(matrix):
  res = 0
  for i in range(len(matrix)):
    for j in range(len(matrix[i])):
      res += matrix[i][j]
  return res

matrix_Sum(mat)

325

In [56]:
np.sum(mat)

325

<div style="direction:rtl">
در آمار ، انحراف معیار، مقدارپراکندگی مجموعه ای از مقادیر است. انحراف استاندارد پایین نشان می دهد که مقادیر نزدیک به میانگین مجموعه هستند ، در حالی که انحراف استاندارد بالا نشان می دهد که مقادیر در دامنه وسیع تری پخش شده اند.
انحراف معیار را در ریاضیات با STD یا همان standard deviation نشان می دهند.
<div style="direction:rtl">
با تحقیق و جست و جو، متدی برای محاسبه ی std در این ماتریس پیدا کنید و انحراف معیار داده های این ماتریس را محاسبه کنید.

In [57]:
np.std(mat)

7.211102550927978

<div style="direction:rtl">
در باره ی axis ها(محور ها) در نامپای تحقیق کنید و axis دیفالت نامپای را معرفی کنید، سپس با کمک axis ها جمع سطر ها وستون های ماتریس را  به دست آورید.

<div style="direction:rtl">
axis دیفالت نامپای در جهت :None

<div style="direction:rtl">
جمع سطر ها:
(هم با متد هم با فانکشن)

In [64]:
def sumofrows(matrix):
  res = []
  for i in range(len(matrix)):
    res.append(sum(matrix[i]))
  return res
sumofrows(mat)


[15, 40, 65, 90, 115]

In [65]:
np.sum(mat, axis = 1)

array([ 15,  40,  65,  90, 115])

<div style="direction:rtl">
جمع ستون ها :
(هم با متد هم با فانکشن)

In [68]:
def sumofcolumns(matrix):
  res = []
  for i in range(len(matrix.transpose())):
    res.append(sum(matrix.transpose()[i]))
  return res
sumofcolumns(mat)

[55, 60, 65, 70, 75]

In [69]:
np.sum(mat, axis = 0)

array([55, 60, 65, 70, 75])

<div style="direction:rtl">
حالا با کمک مفهومی که از محور ها در عملیات های نامپای فرا گرفته اید، سعی کنید با دستور concatenate دو ماتریس زیر را یک بار در جهت محور عمودی و یک بار در جهت محور افقی بهم بچسبانید.

In [70]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
b = np.arange(1,10).reshape(3,3).transpose()
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

<div style="direction:rtl">
چسباندن در راستای افقی:

In [75]:
np.concatenate((a, b), 1)

array([[1, 2, 3, 1, 4, 7],
       [4, 5, 6, 2, 5, 8],
       [7, 8, 9, 3, 6, 9]])

<div style="direction:rtl">
چسباندن در راستای عمودی:

In [76]:
np.concatenate((a, b), 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

<div style="direction:rtl">

## موفق باشید.